<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPRURYAW0060" name="com.epam.test.calculator.PositivTest" tests="8" failures="0" timestamp="16 Mar 2018 09:14:20 GMT" time="0.030" errors="3">
  <testcase name="sumTest" time="0.000" classname="com.epam.test.calculator.PositivTest"/>
  <testcase name="sumTest" time="0.000" classname="com.epam.test.calculator.PositivTest"/>
  <testcase name="testSin" time="0.007" classname="com.epam.test.calculator.PositivTest">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: testSin([Parameter{index=0, type=double, declaredAnnotations=[@org.testng.annotations.Optional(value=null)]}])
Arguments: [null]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: testSin([Parameter{index=0, type=double, declaredAnnotations=[@org.testng.annotations.Optional(value=null)]}])
Arguments: [null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testSin -->
  <testcase name="testCtg" time="0.014" classname="com.epam.test.calculator.PositivTest">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: testCtg([Parameter{index=0, type=double, declaredAnnotations=[@org.testng.annotations.Optional(value=null)]}])
Arguments: [null]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: testCtg([Parameter{index=0, type=double, declaredAnnotations=[@org.testng.annotations.Optional(value=null)]}])
Arguments: [null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testCtg -->
  <testcase name="sumTest" time="0.000" classname="com.epam.test.calculator.PositivTest"/>
  <testcase name="testPow" time="0.003" classname="com.epam.test.calculator.PositivTest"/>
  <testcase name="testTg" time="0.003" classname="com.epam.test.calculator.PositivTest">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: testTg([Parameter{index=0, type=double, declaredAnnotations=[@org.testng.annotations.Optional(value=null)]}])
Arguments: [null]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: testTg([Parameter{index=0, type=double, declaredAnnotations=[@org.testng.annotations.Optional(value=null)]}])
Arguments: [null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:982)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- testTg -->
  <testcase name="sumTest" time="0.003" classname="com.epam.test.calculator.PositivTest"/>
</testsuite> <!-- com.epam.test.calculator.PositivTest -->
